.global __binary_main_js_start
__binary_main_js_start:
        .incbin "main.js"
        .global __binary_main_js_end
__binary_main_js_end:
.global __binary_Makefile_start
__binary_Makefile_start:
        .incbin "Makefile"
        .global __binary_Makefile_end
__binary_Makefile_end:
.global __binary_main_cc_start
__binary_main_cc_start:
        .incbin "main.cc"
        .global __binary_main_cc_end
__binary_main_cc_end:
.global __binary_lo_cc_start
__binary_lo_cc_start:
        .incbin "lo.cc"
        .global __binary_lo_cc_end
__binary_lo_cc_end:
.global __binary_lo_h_start
__binary_lo_h_start:
        .incbin "lo.h"
        .global __binary_lo_h_end
__binary_lo_h_end:
.global __binary_globals_d_ts_start
__binary_globals_d_ts_start:
        .incbin "globals.d.ts"
        .global __binary_globals_d_ts_end
__binary_globals_d_ts_end:
.global __binary_jsconfig_json_start
__binary_jsconfig_json_start:
        .incbin "jsconfig.json"
        .global __binary_jsconfig_json_end
__binary_jsconfig_json_end:
.global __binary_lib_core_api_js_start
__binary_lib_core_api_js_start:
        .incbin "lib/core/api.js"
        .global __binary_lib_core_api_js_end
__binary_lib_core_api_js_end:
.global __binary_lib_curl_api_js_start
__binary_lib_curl_api_js_start:
        .incbin "lib/curl/api.js"
        .global __binary_lib_curl_api_js_end
__binary_lib_curl_api_js_end:
.global __binary_lib_libssl_api_js_start
__binary_lib_libssl_api_js_start:
        .incbin "lib/libssl/api.js"
        .global __binary_lib_libssl_api_js_end
__binary_lib_libssl_api_js_end:
.global __binary_lib_pthread_api_js_start
__binary_lib_pthread_api_js_start:
        .incbin "lib/pthread/api.js"
        .global __binary_lib_pthread_api_js_end
__binary_lib_pthread_api_js_end:
.global __binary_lib_sqlite_api_js_start
__binary_lib_sqlite_api_js_start:
        .incbin "lib/sqlite/api.js"
        .global __binary_lib_sqlite_api_js_end
__binary_lib_sqlite_api_js_end:
.global __binary_lib_zlib_api_js_start
__binary_lib_zlib_api_js_start:
        .incbin "lib/zlib/api.js"
        .global __binary_lib_zlib_api_js_end
__binary_lib_zlib_api_js_end:
.global __binary_lib_asm_js_start
__binary_lib_asm_js_start:
        .incbin "lib/asm.js"
        .global __binary_lib_asm_js_end
__binary_lib_asm_js_end:
.global __binary_lib_bench_js_start
__binary_lib_bench_js_start:
        .incbin "lib/bench.js"
        .global __binary_lib_bench_js_end
__binary_lib_bench_js_end:
.global __binary_lib_binary_js_start
__binary_lib_binary_js_start:
        .incbin "lib/binary.js"
        .global __binary_lib_binary_js_end
__binary_lib_binary_js_end:
.global __binary_lib_curl_js_start
__binary_lib_curl_js_start:
        .incbin "lib/curl.js"
        .global __binary_lib_curl_js_end
__binary_lib_curl_js_end:
.global __binary_lib_ffi_js_start
__binary_lib_ffi_js_start:
        .incbin "lib/ffi.js"
        .global __binary_lib_ffi_js_end
__binary_lib_ffi_js_end:
.global __binary_lib_fs_js_start
__binary_lib_fs_js_start:
        .incbin "lib/fs.js"
        .global __binary_lib_fs_js_end
__binary_lib_fs_js_end:
.global __binary_lib_gen_js_start
__binary_lib_gen_js_start:
        .incbin "lib/gen.js"
        .global __binary_lib_gen_js_end
__binary_lib_gen_js_end:
.global __binary_lib_libssl_js_start
__binary_lib_libssl_js_start:
        .incbin "lib/libssl.js"
        .global __binary_lib_libssl_js_end
__binary_lib_libssl_js_end:
.global __binary_lib_path_js_start
__binary_lib_path_js_start:
        .incbin "lib/path.js"
        .global __binary_lib_path_js_end
__binary_lib_path_js_end:
.global __binary_lib_proc_js_start
__binary_lib_proc_js_start:
        .incbin "lib/proc.js"
        .global __binary_lib_proc_js_end
__binary_lib_proc_js_end:
.global __binary_lib_repl_js_start
__binary_lib_repl_js_start:
        .incbin "lib/repl.js"
        .global __binary_lib_repl_js_end
__binary_lib_repl_js_end:
.global __binary_lib_sqlite_js_start
__binary_lib_sqlite_js_start:
        .incbin "lib/sqlite.js"
        .global __binary_lib_sqlite_js_end
__binary_lib_sqlite_js_end:
.global __binary_lib_untar_js_start
__binary_lib_untar_js_start:
        .incbin "lib/untar.js"
        .global __binary_lib_untar_js_end
__binary_lib_untar_js_end:
.global __binary_lib_zlib_js_start
__binary_lib_zlib_js_start:
        .incbin "lib/zlib.js"
        .global __binary_lib_zlib_js_end
__binary_lib_zlib_js_end:

