
// [do not edit,<auto-generated />]
// This file has been automatically generated (abi target), please do not
// change unless you disable auto-generation -- see doc/WORK.E.1.md.
// This binding's own code never writes v8:: directly, or even touches
// it indirectly -- lo_abi_v8.cc is the only file allowed to (LO_ABI_V8_
// REGISTER below calls a fully portable, engine-agnostic function; the
// real v8:: work happens entirely inside lo_abi_v8.cc, compiled once
// into the runtime, not into this binding -- see lo_abi.h's own comment
// on lo_abi_v8_register_binding for what this replaced and why).

#include "lo_abi.h"

#include <em_inflate.h>



static const lo_type_t inflate_params[] = { LO_POINTER, LO_U32, LO_POINTER, LO_U32 };
static int32_t inflate_lo_fast(uint64_t p0, uint32_t p1, uint64_t p2, uint32_t p3) {
  typedef uint64_t (*F)(uint64_t, uint64_t, uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)em_inflate)((uint64_t)p0, (uint64_t)p1, (uint64_t)p2, (uint64_t)p3);
  return (int32_t)rv;
}
static const lo_fn_desc_t inflate_fns[] = {
  { "inflate", LO_I32, inflate_params, 4, (void*)em_inflate, (void*)inflate_lo_fast, nullptr, 0 },
};

LO_REGISTER(inflate) {
  lo_status_t status = lo_register_functions(engine, exports, inflate_fns,
    sizeof(inflate_fns) / sizeof(inflate_fns[0]));
  if (status != LO_OK) return status;
  return LO_OK;
}

LO_ABI_V8_REGISTER(inflate)
