
// [do not edit,<auto-generated />]
// This file has been automatically generated (abi target), please do not
// change unless you disable auto-generation -- see doc/WORK.E.1.md.
// This binding's own code never writes v8:: directly, or even touches
// it indirectly -- lo_abi_v8.cc is the only file allowed to (LO_ABI_V8_
// REGISTER below calls a fully portable, engine-agnostic function; the
// real v8:: work happens entirely inside lo_abi_v8.cc, compiled once
// into the runtime, not into this binding -- see lo_abi.h's own comment
// on lo_abi_v8_register_binding for what this replaced and why).

#include "lo_abi.h"

#include <sys/epoll.h>
#include <unistd.h>
#include <sys/prctl.h>
#include <errno.h>


#ifdef __linux__
#ifndef __GLIBC__
#include <sys/syscall.h>

static int epoll_pwait2(int epfd, struct epoll_event *events, int maxevents,
    const struct timespec *timeout, const sigset_t *sigmask) {
  return syscall(SYS_epoll_pwait2, epfd, events, maxevents, timeout, sigmask, sizeof(sigset_t));
}
#endif
#endif


static const lo_type_t create_params[] = { LO_I32 };
static const lo_type_t modify_params[] = { LO_I32, LO_I32, LO_I32, LO_BUFFER };
static const lo_type_t wait_params[] = { LO_I32, LO_BUFFER, LO_I32, LO_I32 };
static const lo_type_t pwait_params[] = { LO_I32, LO_BUFFER, LO_I32, LO_I32, LO_BUFFER };
static const lo_type_t pwait2_params[] = { LO_I32, LO_POINTER, LO_I32, LO_POINTER, LO_POINTER };
static const lo_type_t close_params[] = { LO_I32 };
static const lo_type_t prctl_params[] = { LO_I32, LO_U32 };
static int32_t create_lo_fast(int32_t p0) {
  typedef uint64_t (*F)(uint64_t);
  uint64_t rv = ((F)(void*)epoll_create1)((uint64_t)(int64_t)p0);
  return (int32_t)rv;
}
static int32_t modify_lo_fast(int32_t p0, int32_t p1, int32_t p2, uint64_t p3) {
  typedef uint64_t (*F)(uint64_t, uint64_t, uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)epoll_ctl)((uint64_t)(int64_t)p0, (uint64_t)(int64_t)p1, (uint64_t)(int64_t)p2, (uint64_t)p3);
  return (int32_t)rv;
}
static int32_t wait_lo_fast(int32_t p0, uint64_t p1, int32_t p2, int32_t p3) {
  typedef uint64_t (*F)(uint64_t, uint64_t, uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)epoll_wait)((uint64_t)(int64_t)p0, (uint64_t)p1, (uint64_t)(int64_t)p2, (uint64_t)(int64_t)p3);
  return (int32_t)rv;
}
static int32_t pwait_lo_fast(int32_t p0, uint64_t p1, int32_t p2, int32_t p3, uint64_t p4) {
  typedef uint64_t (*F)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)epoll_pwait)((uint64_t)(int64_t)p0, (uint64_t)p1, (uint64_t)(int64_t)p2, (uint64_t)(int64_t)p3, (uint64_t)p4);
  return (int32_t)rv;
}
static int32_t pwait2_lo_fast(int32_t p0, uint64_t p1, int32_t p2, uint64_t p3, uint64_t p4) {
  typedef uint64_t (*F)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)epoll_pwait2)((uint64_t)(int64_t)p0, (uint64_t)p1, (uint64_t)(int64_t)p2, (uint64_t)p3, (uint64_t)p4);
  return (int32_t)rv;
}
static int32_t close_lo_fast(int32_t p0) {
  typedef uint64_t (*F)(uint64_t);
  uint64_t rv = ((F)(void*)close)((uint64_t)(int64_t)p0);
  return (int32_t)rv;
}
static int32_t prctl_lo_fast(int32_t p0, uint32_t p1) {
  typedef uint64_t (*F)(uint64_t, uint64_t);
  uint64_t rv = ((F)(void*)prctl)((uint64_t)(int64_t)p0, (uint64_t)p1);
  return (int32_t)rv;
}
static const lo_fn_desc_t epoll_fns[] = {
  { "create", LO_I32, create_params, 1, (void*)epoll_create1, (void*)create_lo_fast, nullptr, 0 },
  { "modify", LO_I32, modify_params, 4, (void*)epoll_ctl, (void*)modify_lo_fast, nullptr, 0 },
  { "wait", LO_I32, wait_params, 4, (void*)epoll_wait, (void*)wait_lo_fast, nullptr, 0 },
  { "pwait", LO_I32, pwait_params, 5, (void*)epoll_pwait, (void*)pwait_lo_fast, nullptr, 0 },
  { "pwait2", LO_I32, pwait2_params, 5, (void*)epoll_pwait2, (void*)pwait2_lo_fast, nullptr, 0 },
  { "close", LO_I32, close_params, 1, (void*)close, (void*)close_lo_fast, nullptr, 0 },
  { "prctl", LO_I32, prctl_params, 2, (void*)prctl, (void*)prctl_lo_fast, nullptr, 0 },
};

LO_REGISTER(epoll) {
  lo_status_t status = lo_register_functions(engine, exports, epoll_fns,
    sizeof(epoll_fns) / sizeof(epoll_fns[0]));
  if (status != LO_OK) return status;
  lo_exports_set_i32(exports, "EPOLLIN", (int32_t)EPOLLIN);
  lo_exports_set_i32(exports, "EPOLLOUT", (int32_t)EPOLLOUT);
  lo_exports_set_i32(exports, "EPOLLERR", (int32_t)EPOLLERR);
  lo_exports_set_i32(exports, "EPOLLHUP", (int32_t)EPOLLHUP);
  lo_exports_set_i32(exports, "EPOLL_CLOEXEC", (int32_t)EPOLL_CLOEXEC);
  lo_exports_set_i32(exports, "EPOLLEXCLUSIVE", (int32_t)EPOLLEXCLUSIVE);
  lo_exports_set_i32(exports, "EPOLLWAKEUP", (int32_t)EPOLLWAKEUP);
  lo_exports_set_i32(exports, "EPOLLONESHOT", (int32_t)EPOLLONESHOT);
  lo_exports_set_i32(exports, "EPOLLET", (int32_t)EPOLLET);
  lo_exports_set_i32(exports, "EPOLL_CTL_ADD", (int32_t)EPOLL_CTL_ADD);
  lo_exports_set_i32(exports, "EPOLL_CTL_DEL", (int32_t)EPOLL_CTL_DEL);
  lo_exports_set_i32(exports, "EPOLL_CTL_MOD", (int32_t)EPOLL_CTL_MOD);
  lo_exports_set_i32(exports, "EAGAIN", (int32_t)EAGAIN);
  lo_exports_set_i32(exports, "PR_SET_TIMERSLACK", (int32_t)PR_SET_TIMERSLACK);
  lo_exports_set_i32(exports, "struct_epoll_event_size", (int32_t)sizeof(epoll_event));
  return LO_OK;
}

LO_ABI_V8_REGISTER(epoll)
